### ISSUE TITLE
Reorganize Docker files

### ISSUE THREAD

**Issue by greyhillman** [hues-platform/python-ehub#91]
The root directory of the project is getting cluttered, especially after the merging of the Docker PR (#14).

It would be nice to have all the Docker related stuff in the `docker` folder and the server-related stuff say in a `server` folder.

**Comment by greyhillman** [comment]
@ralphevins 
I think the best solution to the problem of having the server code inside this project as well as the actual code is to create another project solely for the server. Instead of having the server and docker code in `hues-platform/python-ehub`, create another repository say `hues-platform/ehub-server` for the docker server. This solves the problem of having too much going on in this repo, which I think is what your real issue is.

One issue with doing that is there needs to be a way of importing the energy hub code into the server repo.

Another issue is that changing the ehub code might break something with the server using that code. But that would happen anyways to any code that uses the ehub.

**Comment by ralphevins** [comment]
I agree, that seems like the best way.
Also gives the option of adapting the server to other purposes in the future.
Let me know how you suggest solving the issues you mention.

**Comment by greyhillman** [comment]
Relevant issue is now #94.
